### ISSUE TITLE
ANSI Escape Code Support

### ISSUE THREAD

**Issue by therealbnut** [buildkite/feedback#106]
Using the ANSI escape codes `\033[105;97;1m` in log output works in terminal, not in the buildkite web interface. It seems to output the appropriate CSS styles, but there is no corresponding classes in the stylesheet.
- `105` light magenta background
- `97` white text
- `1` bold

I'm adding this issue at the request of @keithpitt. I'm now using `\x1b[31;40;1m` which works for me and looks fabulous :wink: (`1` is included, but either redundant in a section heading or still not working)

![screen shot 2015-07-01 at 7 03 03 pm](https://cloud.githubusercontent.com/assets/635596/8469115/9cb1cb12-20b8-11e5-99c3-bffa012dd454.png)

Thanks!

As an aside we were doing this because we had too many sections and it was difficult to differentiate the most important ones. It would be nice to have sections inside sections, perhaps:

```
---- Section
--- Subsection
```

it could also just be that our build could be better organised.

**Comment by keithpitt** [comment]
Thanks for this! I'll take a look and see if we can expand the colors supported :+1:

**Comment by therealbnut** [comment]
Thanks :)

**Comment by Xcapee** [comment]
I wonder did this go anywhere. I have just run into a similar issue. Standard terminal colours for failed builds like  `\033[91m` produce spans with class styles `term-fgi91` but there is no corresponding `.term-fgi91` in any stylesheet.

I have verified that no environment or command line flags are being used to suppress colour. I'm a bit stumped.

**Comment by keithpitt** [comment]
@Xcapee it could just be that we're missing some CSS classes to handle the missing terminal sequences! We did some upgrades to our terminal renderer recently which results in a to of new class names being added that wen't before (one's like bold, etc). If you can email us (hello@buildkite.com) some build outputs that are missing some classes I'm happy to take a look!

Also @therealbnut if you wanna do this as well that's cool.

I'll close this one for now since we've got a path to move forward :)
