### ISSUE TITLE
Rebuild and Retry buttons are very similar

### ISSUE THREAD

**Issue by abraham-chan** [buildkite/feedback#183]
Maybe it's just me, but three times now I've clicked rebuild when I meant to only retry a single container...

![screen shot 2016-08-29 at 1 29 20 pm](https://cloud.githubusercontent.com/assets/10610335/18040053/a7a55cd2-6dec-11e6-9834-8a14fd549d20.png)
![screen shot 2016-08-29 at 1 29 25 pm](https://cloud.githubusercontent.com/assets/10610335/18040054/a7a73534-6dec-11e6-838f-be5843030d75.png)

**Comment by j-clark** [comment]
i was about to submit a similar issue. i would also note that it's a little surprising that Retry for an individual step has to be confirmed with an alert box, but Rebuild for the entire project does not. i would prefer those be swapped

**Comment by keithpitt** [comment]
Totally! I've done this myself a few times as well. We put a confirmation box up on "retry" mostly because it's a destructive action (we delete jobs and artifacts). Ideally in the future we retained that information so we wouldn't need to get a confirmation. Rebuilds don't have one since once you're taken to the new build, you can quickly hit "cancel" on it before it doesn't anything bad.

But I agree, we should make them more consistent and not look so much the same!

**Comment by keithpitt** [comment]
👋 sorry for the late reply to this one! Earlier on in the year we made some changes to how retries are handled:

https://building.buildkite.com/new-in-buildkite-job-retries-3f60a8d45ed2

Retry buttons have a different icon now:

<img width="395" alt="image" src="https://user-images.githubusercontent.com/25882/48999828-bd678f00-f192-11e8-9c1a-672c980ee357.png">

Hopefully that's enough! (you can also turn off retries for some steps that you don't want to allow retries on at all)

```
steps:
  - command: "test.sh"
    retry:
      manual: false
```
