### ISSUE TITLE
Hire a support engineer in a different time zone

### ISSUE THREAD

**Issue by shuber** [buildkite/feedback#190]
We're based in San Francisco and I believe most of the Buildkite team is based out of Australia. 

Occasionally Buildkite has issues in the middle of the night for you guys in the Australia time zone. It would be nice to have a support engineer that is accessible at that time since those are peak hours for us over here and we rely heavily on Buildkite to test and deploy our codebase.

**Comment by keithpitt** [comment]
Hey Sean, thanks for this feedback! This is something we've been acutely aware of ever since we launched Buildkite.

**Buildkite shouldn't be an Australia company, but an Internet company, and as such, we should have support that responds at all times of the day. The internet isn't 9-5 AEST.**

I know how frustrating it is to have a problem and not get a response for a few hours. Living in Australia I get this most days when communicating with US companies (since all the tools I use are mostly run by US companies). We don't want to be like those companies. We can do better!

So rest assured, we know, and we're trying our hardest to fix it. We're having one of our team members work remote from Canada soon, so there will be someone around to answer questions during the day in a US-ish timezone. Next step is for us to solve the problem more permanently.

Sorry again that no one was around to help you out today! That was our failing, and we should do better!
