### ISSUE TITLE
How to delete an account?

### ISSUE THREAD

**Issue by vorg** [buildkite/feedback#199]
Hi, how do i delete my account? Can't find anything in Personal Settings.

**Comment by keithpitt** [comment]
@vorg hey hey! Currently we don't have a button to delete your own user account, but if you shoot an email over to hello@buildkite.com I'll be able to do it on our end for you!

**Comment by kevinmichaelchen** [comment]
Has this changed post-GDPR?

**Comment by meetDeveloper** [comment]
@keithpitt Registering issue for not allowing deletion of account post GDPR

**Comment by keithpitt** [comment]
@kevinmichaelchen @meetDeveloper thanks for the questions! We still don't have a way for you to delete your user account within the app, but if you email support, we'll get it done within 1-2 business days.

I've read through the GDPR, and I don't believe that we're in breach of it by not having a button inside the application to delete your own account. I know it's specifically calls out "without undue delay", and I'm pretty certain that emailing support wouldn't be considered that.

Not trying to make excuses, but if you've got a different take on what our obligations are, I'm keen to hear them!

One thing we *should* do though is at least have a FAQ or a link in settings that tells you the steps you need to take.

**Comment by meetDeveloper** [comment]
@keithpitt I think asking user to specifically mail to delete their own account is not justice to them. You can provide delete button, and then tell them it will take 2 days to delete account, so that their work is massively reduce, you also know that asking them to mail will automatically decrease people doing deletion.

**Comment by meetDeveloper** [comment]
@keithpitt I think asking user to specifically mail to delete their own account is not justice to them. You can provide delete button, and then tell them it will take 2 days to delete account, so that their work is massively reduce, you also know that asking them to mail will automatically decrease people doing deletion.

**Comment by wulffeld** [comment]
@keithpitt You're probably right but it's just so annoying to have to spend time looking around the interface to see if there's already a built-in feature for it, then looking through the docs, then googling it to get directed here etc. etc.

While buildkite wasn't what I was looking for now I might come back to revisit in the future though this experience of not being able to delete my account makes me reconsider. I hate being stuck with a foot in the door when leaving a shop.

**Comment by rootkea** [comment]
@wulffeld This is clearly a dark pattern. Very disappointing! I'll never reuse buildkite after I shoot the mail.

**Comment by keithpitt** [comment]
@rootkea I disagree! We actioned your deletion request in 15 minutes. I wouldn't consider this a dark patten. A bit crappy, I admit, but we're not trying to trick you into a particular behaviour (which is what a dark pattern is)

**Comment by sgammon** [comment]
@keithpitt it's the principle of the matter, especially because it's easy to accidentally create an extra Buildkite account with the following UX:

1) join a new company
2) create a new account under your work email (in my case, my _previous_ account was under a work email, so I didn't feel comfy logging in that way)
3) learn that you can't link your github account because it is already linked to the old user
4) realize that you probably can't use SSO now, but whatever
5) so you add the new work email to your other (older) Buildkite account, figuring there will be some process to fix this
6) you can't add the _new_ work email to the _old_ account because the _new_ account has claimed the email
7) look around the UI to delete the _new_ account from an incognito window, because you're now juggling two sessions and trying to just reconcile on one f*cking account because of a limitation mentioned nowhere
8) arrive at this ticket to realize that you, the CTO, has literally said _no you disagree_ (lol) with your _users_

i mean okay, yes, if we are going to get pedantic about it, there is nothing different (_legally_ speaking) between emailing support and a button in the UI - so long as you catch up and always stay on top of things. for instance, right now, in PST (during a pandemic), it's 1:55pm there, on a Friday, which means you _should_ get my incoming account deletion request almost immediately, and _presumably_ respond to it immediately to help me with this situation.

because, of course, you have essentially set yourself up to _have_ to do that, since I cannot even properly enqueue an account deletion request without speaking to support (a process which likely just files a ticket anyway - so why can't you just make a button to do that, that releases my email address?).

my only alternative, because of this mix of dark patterns and shitty UX, is to _change_ my email on my new account to some other value, and then reclaim the email in the _old_ account, and jettison my new one. so enjoy that in your database, because you leave me no reasonable way to be a good data citizen:

<img width="884" alt="Screen Shot 2020-04-09 at 10 58 49 PM" src="https://user-images.githubusercontent.com/171897/78966835-aee2f480-7ab5-11ea-96bd-73fee32be436.png">


you may also want to look into counting + addresses as entirely separate emails. this will probably allow billing fraud/abuse with your trial system. fyi

**Comment by sgammon** [comment]
@keithpitt it's the principle of the matter, especially because it's easy to accidentally create an extra Buildkite account with the following UX:

1) join a new company
2) create a new account under your work email (in my case, my _previous_ account was under a work email, so I didn't feel comfy logging in that way)
3) learn that you can't link your github account because it is already linked to the old user
4) realize that you probably can't use SSO now, but whatever
5) so you add the new work email to your other (older) Buildkite account, figuring there will be some process to fix this
6) you can't add the _new_ work email to the _old_ account because the _new_ account has claimed the email
7) look around the UI to delete the _new_ account from an incognito window, because you're now juggling two sessions and trying to just reconcile on one f*cking account because of a limitation mentioned nowhere
8) arrive at this ticket to realize that you, the CTO, has literally said _no you disagree_ (lol) with your _users_

i mean okay, yes, if we are going to get pedantic about it, there is nothing different (_legally_ speaking) between emailing support and a button in the UI - so long as you catch up and always stay on top of things. for instance, right now, in PST (during a pandemic), it's 1:55pm there, on a Friday, which means you _should_ get my incoming account deletion request almost immediately, and _presumably_ respond to it immediately to help me with this situation.

because, of course, you have essentially set yourself up to _have_ to do that, since I cannot even properly enqueue an account deletion request without speaking to support (a process which likely just files a ticket anyway - so why can't you just make a button to do that, that releases my email address?).

my only alternative, because of this mix of dark patterns and shitty UX, is to _change_ my email on my new account to some other value, and then reclaim the email in the _old_ account, and jettison my new one. so enjoy that in your database, because you leave me no reasonable way to be a good data citizen:

<img width="884" alt="yo" src="https://user-images.githubusercontent.com/171897/78966942-fa959e00-7ab5-11ea-8d77-a3756df3b7f2.png">

you may also want to look into counting + addresses as entirely separate emails. this will probably allow billing fraud/abuse with your trial system. fyi

**Comment by sgammon** [comment]
@keithpitt by the way yes it is a dark pattern. deal with reality or fantasy, your choice

**Comment by keithpitt** [comment]
@sgammon thanks for writing all that down. I agree with you. I'll see what I can do.

**Comment by keithpitt** [comment]
@sgammon we fixed this. You can now remove your own account via the UI. Go here https://buildkite.com/user/settings and scroll to the bottom of the page. 🚀 

Thanks again!
