### ISSUE TITLE
Display user that cancelled a build

### ISSUE THREAD

**Issue by mgood** [buildkite/feedback#220]
When a developer cancels a build it would be useful for us to know who it was. It's not always clear why they cancelled it, so it would be helpful to follow up with them to see what happened.

**Comment by keithpitt** [comment]
Oh yeah, this is some good feedback! We do actually store who cancelled the build, so we could definitely propagate that information up to the UI. The build page is due in for a refresh soon, so hopefully when we update it we can roll this into it!

**Comment by geoff-kruss** [comment]
@keithpitt my apologies for reviving quite an old issue, but my feedback builds on this. I would very much like to be able to distinguish between a failed build vs a cancelled build, even when the build was cancelled due to buildkite cooperating with my concurrency restraints (ie. when a build is cancelled because a newer build started and I have this option checked in the pipeline settings, instead of being cancelled explicitly by a user)

Furthermore I don't think that cancelled builds should be used when calculating the build reliability percentage ? Currently it appears as if cancelled builds are counted towards this metric. There's probably some discussion to be had around this as it might not be so straight foward but definitely worth thinking about I think.

**Comment by rmtobin** [comment]
I was about to file a new issue then saw this - cancelled and failed statuses should be more distinct from each other. Cancelling a build is not always a "bad" state (more like a neutral state), but the UI makes it look like a failure.

**Comment by eredi93** [comment]
@keithpitt any update on this?

**Comment by keithpitt** [comment]
@eredi93 we just shipped a change that shows who canceled the build: https://buildkite.com/changelog/33-show-why-a-build-was-canceled

I know it doesn't address all the feedback in this issue (nothing around how canceled builds look or how they're treated in the pipeline stats) but I think this is a good first step!

**Comment by eredi93** [comment]
This is great. Thanks!
