### ISSUE TITLE
Agent Targeting: Partial wildcard matching

### ISSUE THREAD

**Issue by sschaetz** [buildkite/feedback#229]
In your docs you guys say:
> Partial wildcard matching (e.g. postgres=1.9* or postgres=*1.9) is not yet supported.

Would be fantastic if we could have this. I'd love to be able to do this: `cpu=Intel(R) Xeon(R)*`

**Comment by sschaetz** [comment]
Oh and I forgot:

`cpu=!Intel(R) Xeon(R)*`

to make sure a lint job does not run on the valuable xeons.

**Comment by keithpitt** [comment]
Hey @sschaetz - good ideas! One way you can structure a setup like that is if you use a `queue` agent targeting rule. So in your example, it sounds like you've some pretty amazing hardware to play with, and you don't want to run the crappy jobs on it. So you could do this:

```yaml
steps:
  - command: "lint.sh"
  - command: "mine-bitcoin.sh"
      agents:
        queue: "xeon"
```

In that example, "lint.sh" will run on any agent running the `default` queue (which is the default if you haven't specified a `--meta-data queue=...` argument to an agent.

On your Intel Xeon machines, you just run the agent like this:

```shell
buildkite-agent start --meta-data queue=xeon
```

That way the `mine-bitcoin.sh` script will only run on your amazing Xeon hardware. So the agent targeting rules become more "opt-in" instead of "opt-out" if that makes sense?

**Comment by keithpitt** [comment]
👋 I might close this one for now. We don't have any current plans to add partial targeting to agent query rules (I figure it'd better to close rather than leave it open forever).

The main reason we'd probably not add it is due to the massive performance hit we'd see. We've taken quite a lot of care to make sure queue targeting is fast, and we've got a pretty good approach currently (we turn the agents query rules into an unordered `Set`, the agent tags into a unordered `Set`, and then do a simple set comparison to see if they match).

Introducing wildcards and other operations will make it pretty complex (version comparison even more so). Even though it's a little bit of a pain to setup, we think the current approach of defining your own tags, and doing simple matches on those is the best solution.

If you want version aware matching @petemounce, you could do something like:

```
buildkite-agent start --tags "postgres_min=9.5"
```

Then have a job that looks for an agent with `postgres_min=9.5`.

I might close this one for now, but we may come back to it later on if we can figure out the technology required to make it fast, and if more customers end up asking for it.

Thanks again for the suggestion @sschaetz, keep 'em coming!
