### ISSUE TITLE
New Feature required - interpolated values in environment definition.

### ISSUE THREAD

**Issue by SydOps** [buildkite/feedback#248]
Could we have the variables defined as below?

```
env:
  ENVIRONMENT: dev1
  TAG_VERSION: ${ENVIRONMENT}-${BUILDKITE_BUILD_NUMBER}
```

**Comment by toolmantim** [comment]
Hi! I don't think this is going to be possible @SydOps, because you'd need to evaluate `ENVIRONMENT` before being able to use it below. You'd either need to define them outside of the pipeline.yml, or repeat them.

You can use interpolation though, in Buildkite Agent 3.0. But it uses the values from the environment which ran the `buildkite-agent pipeline upload` command.
