### ISSUE TITLE
Enforce 2-factor authentication on all users in organization

### ISSUE THREAD

**Issue by JensRantil** [buildkite/feedback#271]
If #270 gets fixed: Enforce 2-factor authentication for all users in an organization. Just like Github supports.

**Comment by JensRantil** [comment]
A workaround is to enable federated login and enforce 2-factor auth through that.

**Comment by eleanorakh** [comment]
Hi @JensRantil, we've just shipped Two-factor authentication! We did want to include the ability to enforce 2fa in an organisation, but I'm afraid this is going to have to wait until the next iteration of 2fa. 

We have added a little UI change in user listing, so you'll be able to see who in your team has 2fa enabled! You can view this in organisation settings > user.

Here's a handy little GraphQL query you can use to search for 2fa status in your org:

```
query {
  organization(slug:"SLUG") {
    name
    members(first: 10) {
      edges {
        node {
          security {
            passwordProtected
            twoFactorEnabled
          }
        }
      }
    }
  }
}
```

**Comment by zegl** [comment]
@eleanorakh Why was this feedback issue closed? It's nice to have a way to query for users without 2FA, but without a way to *enforce* 2FA I don't see how this issue has been fulfilled.

**Comment by keithpitt** [comment]
@zegl we closed it since we're now tracking this issue internally. Even though there's no first class way to enforce 2FA, you could throw something yourself together with the GraphQLAPI (using a combination of the query above, and the `organizationMemberDelete` mutation to remove a user that doesn't have 2FA enabled) and a scheduled build to check your users every day or so.

We've got some (much more exciting) stuff cooking at the moment, so enforced 2FA isn't something we have an ETA on currently I'm afraid! We'll definitely reach out through this ticket and our changelog when we do tackle this one though! 👍

**Comment by robinator** [comment]
Just curious if there's a way to enforce auth through one of the SSO providers?  E.g. all users _must_ authenticate via google sso.  That way you can just enforce 2FA on the google / IDP side of the process.
