### ISSUE TITLE
Confirmation on Rebuild button

### ISSUE THREAD

**Issue by sarmad90** [buildkite/feedback#311]
Buildkite needs to have a confirmation box on Rebuild (whole build — all tests) button. I’ve mistakenly started building the whole build again a few times now when I only wanted to rebuild a single failure. There’s a confirmation box when we try to retry a single test, but not on the Rebuild button.

**Comment by keithpitt** [comment]
@sarmad90 thanks for the suggestion! It's a good idea, and we struggle with things like this. When we add confirmations, people ask for them to be removed. When we don't have them, people ask for them to be added. So there's no real *right* answer.

The approach we've settled on was "assume the user meant to do it". Since you can easily cancel a build if you accidentally hit "Rebuild" - we think that's an OK answer. We actually did go to add it, but ended up backing out of it: https://github.com/buildkite/frontend/pull/414#issuecomment-368379770

Sorry to not have the answer you were hoping for! (hopefully I've given some context though as to our thinking).

Thanks again for posting - would love to hear any other ideas you have!
