### ISSUE TITLE
Bug: Docker V3 Buildkite Agent doesn't have agent binary 

### ISSUE THREAD

**Issue by baank** [buildkite/feedback#356]
So in the V2 Dockerfile there used to be this line:
`RUN curl -Lfs -o /usr/local/bin/buildkite-agent https://download.buildkite.com/agent/stable/latest/buildkite-agent-linux-amd64 \
    && chmod +x /usr/local/bin/buildkite-agent \`

Which has now been removed from the V3 Dockerfile:
https://github.com/buildkite/agent/tree/master/packaging/docker/linux

In favour of:
`COPY ./buildkite-agent /usr/local/bin/buildkite-agent`

Which fails because that binary doesn't exist. Maybe I am doing something weird but all I want is to be able to customise the Docker build agent e.g. add SBT/Java like the documentation leads me to believe.

**Comment by toolmantim** [comment]
Ah, sorry about that! That file is now sourced from the build artifacts in the agent build process. You can use the following line in your own scripts to download the latest stable agent binary:

```dockerfile
ADD https://download.buildkite.com/agent/stable/latest/buildkite-agent-linux-amd64 /usr/local/bin/buildkite-agent
```

It might be best to email support with this issue in the future, or raise an issue on the buildkite/agent repository. This repo's more for general feedback rather than specific technical problems. But either way, sorry for the confusion 🙏🏼

**Comment by toolmantim** [comment]
Perhaps there's some docs we should update along with this? Which documentation were you referring to?
