### ISSUE TITLE
Bug: ECR Plugin is broken if used according to documentation

### ISSUE THREAD

**Issue by baank** [buildkite/feedback#359]
Described in this bug:
https://github.com/buildkite-plugins/ecr-buildkite-plugin/issues/14

The documentation refers to a parameter: "region".

But actually this parameter is not present in the current 1.1.3 tag of the plugin:
https://github.com/buildkite-plugins/ecr-buildkite-plugin/tree/v1.1.3

Which causes this plugin to not work in any other region except US East.

**Comment by toolmantim** [comment]
Thanks, and sorry about that. buildkite-plugins/ecr-buildkite-plugin#14 is now fixed and we've put out a v1.1.4.

It's probably best to stick with the issues in the repos themselves, rather than this feedback repository. Otherwise there's going to be lots of housekeeping to keep it all up-to-date and current.
