### ISSUE TITLE
Question: Is there a way to get artifacts automatically

### ISSUE THREAD

**Issue by liam-lai** [buildkite/feedback#367]
Hi There, 

Story is, we are creating our own dashbroad for End2End test report. And now all the artifacts I click it the URL itself generated by random hash code ( I guess ), and hard to predict or auto get the right URL for our testing result which put on Buildkite S3. Is there a way to Get the URL after every build happens?

Cheers,
Liam

**Comment by toolmantim** [comment]
Hi Liam! This might be best for support, rather than the feedback repo, but I’ll try to answer you here.

The artifacts are signed for security, but if you wanted maybe you could upload directly to your own S3 bucket yourself, with a known URL?

The “aws” command line tool (which comes in our Elastic CI Stack for AWS if you’re using that) makes it fairly straightforward:

```
aws s3 sync my-file.txt s3://my-bucket/my-file.txt
```

You can find some more examples in the docs for that tool: https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html#examples

We don’t have anything like that built-in I’m afraid.
