### ISSUE TITLE
Support ticket 4208

### ISSUE THREAD

**Issue by ticky** [buildkite/feedback#479]

**Comment by phazel** [comment]
Hi there (I assume you're Jessica?). Josh (@nullobject) sent me on your response to our support ticket. I'm Courtney, and this is definitely my Github account. It's possible that the other BuildKite account is a leftover from a previous employer, and I no longer have the password for it since it was in the LastPass account I had with them.

**Comment by phazel** [comment]
Also you seem cool and I'm adding you to twitter.

**Comment by ticky** [comment]
Thanks for verifying, Courtney. You should now be able to connect your GitHub account to Buildkite. Sorry for the trouble! 😃
