### ISSUE TITLE
switch back to github for feature requests

### ISSUE THREAD

**Issue by nhooyr** [buildkite/feedback#495]
It adds a big barrier to feature requests and feedback if you have to create a new account to deliver it.

Whats GitHub missing? It has reactions so you can gauge which features are most wanted.

**Comment by toolmantim** [comment]
You can find a full write up of why here: https://forum.buildkite.community/t/why-were-evaluating-discourse/120

We're hoping to improve the forum so you can log in via Buildkite, because like you said it does create a barrier to have to create a new account.

But GitHub hasn't been a great place to work with feature suggestions. It's easy to submit, but hard to sort through, vote, and build a community around. We've no plans to switch back yet, and your best bet is using the forum.
