### ISSUE TITLE
Specify agents to run only on PR's

### ISSUE THREAD

**Issue by santouras** [buildkite/feedback#51]
I guess this is semi related to #32.

We want to build our PR's, but not block our master/staging builds as these are doing actual deploys. To this end we'd like to specify that one agent is dedicated to building just PR's, but this is tricky to setup.

I see a couple of ways around this:
- "Don't build these branches" option, so we can let an agent run on all branches EXCEPT master/staging
- "Build only PR's" option. This would solve the issue completely for us
- setup another server and project that builds all pushes but doesn't do deploys. Less than ideal, duplication and costs

Any other suggestions would be really helpful!

**Comment by therealbnut** [comment]
> We've been toying with the idea of having branch-level prioritisation for builds
@keithpitt hey, we're interested in prioritising builds with PRs, is this possible, and has it been implemented?

**Comment by keithpitt** [comment]
Well this is embarrassing! We haven't done branch prioritisation yet @therealbnut :( We've spent a lot of time recently working on our Elastic CI stuff (https://github.com/buildkite/elastic-ci-stack-for-aws) with the idea of being "what if capacity wasn't an issue". But this totally doesn't work for everyone, and branch prioritisation is something we really want to do.

We're hiring more people in the next few months, so hopefully we'll have more capacity to start making these sorts of changes!

Sorry again for taking and embarrassingly long time on this...

**Comment by therealbnut** [comment]
@keithpitt no problem, thanks for the speedy reply

**Comment by keithpitt** [comment]
I did some more thinking on this, and I think I have a potential (hacky) solution to it right now...

First thing you need to do is create a pool of agents dedicated to running builds for the thing you want to prioritise. For example, you'd create a "pull request agent pool" and a "everything else" agent pool. You'd allocate more agents in the "pull request agent pool" if you'd like to prioritise that.

Then you can use our Dynamic Pipelines upload feature: https://buildkite.com/docs/guides/uploading-pipelines#dynamic-pipelines to dynamically change the agents for steps to either the dedicated queue, or the regular queue, depending on the value of `BUILDKITE_BRANCH` or `BUILDKITE_PULL_REQUEST`

So have a base pipeline like this:

```yaml
# .buildkite/pipeline.yml

steps:
  - command: "test.sh"
    agents:
      queue: "$QUEUE"
  - wait
  - command: "test2.sh"
    agents:
      queue: "$QUEUE"
```

```shell
# .buildkite/pipeline.sh

QUEUE="default"
if [[ "$BUILDKITE_BRANCH" == "master" ]]; then
  QUEUE="master-pool"
fi

cat .buildkite/pipeline.yml | sed -e 's/${QUEUE}/$QUEUE/g'
```

Then instead of doing `buildkite-agent pipeline upload` as your first step, run this: `.buildkite/pipeline.sh | buildkite-agent pipeline upload`

So it's not _true_ prioritisation, but this does allow you to dynamically change which agents are used depending on the branch.
