### ISSUE TITLE
Unable to see who opened the gate on a build

### ISSUE THREAD

**Issue by cirode** [buildkite/feedback#73]
When you have a pipeline set up with a "click to continue" step, there is no way to determine who clicked the gate to open it

In our case this means that we cannot trace who deploys to production

**Comment by lsimoneau** [comment]
Very much :+1: on this. We'd even prefer a step further and being able to restrict clicking "Continue" to a specific user or set of users, but just seeing who did it would be helpful.

**Comment by keithpitt** [comment]
![screen shot 2016-02-24 at 8 12 27 am](https://cloud.githubusercontent.com/assets/25882/13266906/5ea08df6-dace-11e5-89e8-5b840189ab75.png)

We gave some love to this feature a few months ago, but I totally forgot to respond to this issue. Sorry! We now show who unblocked the pipeline. You can also now tweak the label, so instead of saying just "Continue" you can make it say "Ship to Production :shipit:"

**Comment by keithpitt** [comment]
@lsimoneau restricting who can click on that button will be possible once we ship our Teams feature!
