### ISSUE TITLE
Build commit in webhooks displays incorrect when manually triggering a build

### ISSUE THREAD

**Issue by mariovisic** [buildkite/feedback#91]
When manually running a build, rather than through a github trigger, the commit that is sent in webhooks is shown as the input that the user gave, rather than the actual sha of the commit. So for example it looks like this now for a manual build:

```json
{
  "build": {
    "commit": "master",
    "branch": "master",
  },
}
```

But looks like this for a build triggered via github.

```json
{
  "build": {
    "commit": "acd4724bc348347a8d7c1f53d7c8242f83bbc76c",
    "branch": "master",
  },
}
```

Is it possible to always show the commit sha, rather than the users input when manually triggering a build?

**Comment by keithpitt** [comment]
Oh hai! This is actually tricky, because we can't actually find out the SHA until the build starts, and by that time, the `build.created` webhook has already been sent. We don't have access to the code, so we can't lookup the HEAD commit on the branch.

We've started storing the actual commit in the `bootstrap.sh` here: https://github.com/buildkite/agent/blob/master/templates/bootstrap.sh#L222

But we don't expose that value that the moment (we should though!). Do you need the SHA in the `build.created` hook? Or if during the build, we updated the commit with the one from the `bootstrap.sh`, and made it available in the `build.finished` webhook, would that be ok?

**Comment by mariovisic** [comment]
Oh hello! *waves*

That makes sense. We only need the commit sha upon a successful `build.finished`. The use case is to have [samson](https://github.com/zendesk/samson) perform deploys for green builds. I'd imagine it may confuse other devs though if you received a `build.created` and then a `build.finished` with different values for `commit`, maybe?

**Comment by keithpitt** [comment]
We've now started sending the actual commit in webhooks for `build.finished`! Thanks for letting us know @mariovisic! :heart:

**Comment by mariovisic** [comment]
Awesome, thank you so much :)
